layout_spectrum: 0.2336197
typography_spectrum: 0.6364124
color:
  saturation: 1
  lightness: 1
  brandStrength: 0.127462
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#211E1F'
    - '#C5C5C5'
    - '#424242'
  rhythmicContrast: 0.6413673
name: Loudinpublic
